### ISSUE TITLE
slide-left effect - old screen title is displayed during animation

### ISSUE THREAD

**Issue by Kra-Kra** [blackberry/bbUI.js#873]
Reported against bbui 0.9.6.145

When you use slide-left effect, during animation process you can see how content of the new screen goes over the content of the old screen, but the title of the new screen is not visible (i.e. not animated) until the effect animation completes. 

As far as I can see, this issue is caused by z-order of the various elements. We have a partial fix which works for us, but may have side effects in some other scenarios

bbui.css

``` CSS
.bb-transition-overlay
{
/* patch start */
  z-index: 1002;
/* patch end */
  position: fixed;
  top: 0px;
  right:0px;
  bottom:0px;
  left:0px;
}

/* patch start */
.bb-transition-hack
{
  z-index: 1001;
}
/* patch end */
```

bbui.js

``` JavaScript
if (effectToApply) {
  // Create our overlay
/* patch start */
  animationScreen._savedClassName = animationScreen.className;
  animationScreen.className += " bb-transition-hack";
/* patch end */
  overlay = document.createElement('div');

/* ... */

      this.overlay = null;
/* patch start */
      this.className = this._savedClassName;
/* patch end */

      // Only remove the screen at the end of animation "IF" it isn't the only screen left
      if (bb.screens.length > 1) {
```
